# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7451c4746919b88db11e1bd8cc26fe23cc058d8b85e38a7349d399e0b868383d7d95367030131aa6de8fc8cc1c855cc4bc1d0904497e9085be4e07cb0f02f448

test:
  secret_key_base: 02d82c81115f2fffabe794a21f9590431900981afe88ecf8659dbcc5dbd4b62a647ccd4edfeea43bb4529a8e6727788273f5c29b5ccab0ac528319c119f548e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
